apiVersion: alibabacloud.com/v1beta
kind: PCAIssuer
metadata:
  labels:
    app.kubernetes.io/name: alibabacloud-privateca-issuer
    app.kubernetes.io/managed-by: kustomize
  name: pcaissuer-sample
spec:
  # TODO(user): Add fields here
