apiVersion: v1
name: alibabacloud-privateca-issuer
version: 1.0.0
appVersion: 1.0.0
description: An addon for cert-manager to sign certificates using AlibabaCloud PCA
keywords:
  - namespace:kube-system
  - releaseName:alibabacloud-privateca-issuer
  - arch:amd64,arm64
home: github.com/AliyunContainerService/alibabacloud-privateca-issuer
sources:
  - github.com/AliyunContainerService/alibabacloud-privateca-issuer